apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: alert-ignore-list
    behavior: merge
    files:
      - ignore_reasons=ignore_reasons.txt

generators:
  - generate-alert-ignore-rules.yaml
